services:
  - type: web
    name: student-schedule-app-full
    env: node
    rootDir: .
    buildCommand: |
      npm install
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.14.0
      - key: RENDER
        value: "true"
